[package]
name = "describe-stack"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "describe-stack"
path = "src/main.rs"

[dependencies]
cmd_lib.workspace = true
serde.workspace = true
serde_json.workspace = true
comfy-table.workspace = true