[package]
name = "slotmap_conn_pool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project-lite = "0.2"
slotmap = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
