[package]
name = "bucket_tables"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
rand.workspace = true
moka.workspace = true
tracing.workspace = true
metrics.workspace = true
