[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
cmd_lib.workspace = true
env_logger.workspace = true
num_cpus.workspace = true
rayon.workspace = true
rlimit.workspace = true
clap.workspace = true
strum.workspace = true
uuid.workspace = true
