[package]
name = "aws_signature"
version = "0.1.0"
edition = "2024"

[features]
testutils = []

[dependencies]
chrono.workspace = true
hmac.workspace = true
sha2.workspace = true
hex.workspace = true
base64.workspace = true

[dev-dependencies]
tokio.workspace = true
