[package]
name = "slotmap_conn_pool"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slotmap.workspace = true
tokio.workspace = true
parking_lot.workspace = true
