[package]
name = "data_blob_tracking"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }

# RPC clients
rpc_client_nss = { workspace = true }
rpc_client_rss = { workspace = true }
