[alias]
xtask = "run --manifest-path ./xtask/Cargo.toml --"

[build]
rustflags = ["--cfg", "tokio_unstable"]

[profile.release]
debug = true

[target.aarch64-unknown-linux-gnu]
rustflags = [
  "-C", "target-cpu=neoverse-v1",
  "-C", "target-feature=+lse,+rcpc",
]
