[package]
name = "rewrk_rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
rpc_client_nss.workspace = true
rpc_client_bss.workspace = true
data_types.workspace = true

anyhow.workspace = true
bytes.workspace = true
colored.workspace = true
futures-util.workspace = true
futures.workspace = true
pin-project-lite.workspace = true
regex.workspace = true
rlimit.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
clap.workspace = true
