[package]
name = "api_server"
version = "0.1.0"
edition = "2021"

[dependencies]
# to debug protobuf as json
# TODO: remove them once the apis are stable
prost-wkt = "0.6"
prost-wkt-types = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.125"

# websocket
soketto = "0.8.0"
tokio-util = { version = "0.7.11", features = ["compat"] }

axum = "0.7.5"
axum-extra = { version = "0.9.3", features = ["protobuf"] }
tokio = { version = "1.39.2", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
prost = "0.13"
bytes = "1.7.1"
thiserror = "1.0.63"
tracing = "0.1.40"
tower-http = { version = "0.5.2", features = ["trace"] }
bytemuck = { version = "1.18.0", features = ["derive"] }

[build-dependencies]
prost-build = "0.13"
prost-wkt-build = "0.6"
