[package]
name = "api_server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.125"
axum = "0.7.7"
axum-extra = { version = "0.9.3", features = ["protobuf"] }
tokio = { version = "1.39.2", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
prost = "0.13"
bytes = "1.7.1"
tracing = "0.1.40"
tower-http = { version = "0.5.2", features = ["trace"] }
console-subscriber = "0.4.0"
nss_rpc_client = { path = "../nss_rpc_client" }
tower = "0.5.1"

[dev-dependencies]
http-body-util = "0.1.2"
