[package]
name = "api_server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
axum-extra = { version = "0.9.3", features = ["protobuf"] }
base64 = "0.22.1"
prost = "0.12.6"
sha-1 = "0.10.1"
tokio = { version = "1.39.2", features = ["full"] }
tracing-subscriber = "0.3.18"
web-socket = "0.7.0"

[build-dependencies]
prost-build = "0.12.6"
