name: ci

on:
  push:
    branches:
    - main
    - axum-dev
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y moreutils

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Load Rust cache
      uses: Swatinem/rust-cache@v2

    - name: Run repo init
      run: cargo xtask repo init

    - name: Run precheckin
      run: cargo xtask precheckin
